version: '3'
services:

  database:
    image: mariadb:latest
    env_file: ./build/envfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "$HOST_DB_PORT:3306"
    volumes:
      #if you insert init data
      #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./data:/var/lib/mysql

  webserver:
    build: build
    # image: centos_server:apache_php71_dev
    image: centos_server:apache_php56_dev
    env_file: ./build/envfile
    volumes:
      - ./project:/var/www
      # - ./log/error.log:/var/log/httpd/error.log
      # - ./log/access.log:/var/log/httpd/access.log
      - ./build/php.ini:/etc/php.ini
      - ./build/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./build/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
    depends_on:
      - database
    # ports:
    #   - "8088:80"
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
    networks:
      - external_nginx_proxy

    # command: /usr/sbin/httpd -DFOREGROUND
  
#settin virtualhost
networks:
  external_nginx_proxy:
    external:
        name: proxy_net
