version: '3'
services:

  # data:
  #   image: busybox
  #   volumes:
  #     - ../mysql:/var/lib/mysql

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: development
      MYSQL_PASSWORD: development
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "23306:3306"
    volumes:
      #if you insert init data
      #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./data:/var/lib/mysql

  webserver:
    build: build
    image: centos_server:apache_php71_dev
    ports:
      - "8090:80"
    volumes:
      - ./project:/var/www
      - ./log/error.log:/var/log/httpd/error.log
      - ./log/access.log:/var/log/httpd/access.log
      - ./build/php.ini:/etc/php.ini
      - ./build/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./build/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: project
      DATABASE_USER: development
      DATABASE_PASSWORD: development
    # command: /usr/sbin/httpd -DFOREGROUND
